/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error': '#dc2626',
        'primary-fixed-dim': '#fed7aa',
        'primary-fixed': '#ffedd5',
        'tertiary-fixed-dim': '#bae6fd',
        'surface-container-high': '#f1f5f9',
        'outline': '#cbd5e1',
        'tertiary-fixed': '#e0f2fe',
        'inverse-on-surface': '#f8fafc',
        'inverse-surface': '#0f172a',
        'inverse-primary': '#ea580c',
        'secondary-fixed-dim': '#e2e8f0',
        'surface': '#ffffff',
        'secondary-fixed': '#f1f5f9',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#ea580c',
        'on-secondary-fixed-variant': '#475569',
        'on-surface': '#0f172a',
        'on-secondary-fixed': '#0f172a',
        'background': '#f8fafc',
        'tertiary-container': '#e0f2fe',
        'surface-bright': '#ffffff',
        'on-primary': '#ffffff',
        'primary': '#ea580c',
        'surface-variant': '#f1f5f9',
        'on-primary-fixed-variant': '#9a3412',
        'secondary-container': '#f1f5f9',
        'primary-container': '#ea580c',
        'on-secondary-container': '#0f172a',
        'on-primary-fixed': '#7c2d12',
        'tertiary': '#0284c7',
        'secondary': '#475569',
        'on-error-container': '#991b1b',
        'surface-container': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#475569',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e2e8f0',
        'surface-dim': '#f1f5f9',
        'on-tertiary-container': '#0369a1',
        'error-container': '#fee2e2',
        'on-primary-container': '#ffffff',
        'on-tertiary-fixed-variant': '#075985',
        'outline-variant': '#e2e8f0',
        'on-tertiary-fixed': '#0c4a6e',
        'surface-container-low': '#f8fafc',
        'on-background': '#0f172a',
        'industrial-border': '#e2e8f0',
        'in-stock': '#16a34a',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'stack-lg': '24px',
        'stack-md': '12px',
        'gutter': '24px',
        'stack-sm': '4px',
        'base': '8px',
        'margin-mobile': '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { 'lineHeight': '32px', 'fontWeight': '700' }],
        'body-lg': ['16px', { 'lineHeight': '24px', 'fontWeight': '400' }],
        'title-md': ['20px', { 'lineHeight': '28px', 'fontWeight': '600' }],
        'display-lg': ['48px', { 'lineHeight': '56px', 'letterSpacing': '-0.02em', 'fontWeight': '800' }],
        'body-sm': ['14px', { 'lineHeight': '20px', 'fontWeight': '400' }],
        'label-caps': ['12px', { 'lineHeight': '16px', 'letterSpacing': '0.05em', 'fontWeight': '600' }],
        'headline-lg': ['32px', { 'lineHeight': '40px', 'letterSpacing': '-0.01em', 'fontWeight': '700' }],
      },
    },
  },
  plugins: [],
};
