/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error': '#ef4444',
        'primary-fixed-dim': '#FF8A1A',
        'primary-fixed': '#ffedd5',
        'tertiary-fixed-dim': '#9ca3af',
        'surface-container-high': '#202020',
        'outline': '#4b5563',
        'tertiary-fixed': '#e5e7eb',
        'inverse-on-surface': '#ffffff',
        'inverse-surface': '#111111',
        'inverse-primary': '#FF6B00',
        'secondary-fixed-dim': '#9ca3af',
        'surface': '#080808',
        'secondary-fixed': '#e5e7eb',
        'on-error': '#ffffff',
        'surface-container-lowest': '#050505',
        'surface-tint': '#FF6B00',
        'on-secondary-fixed-variant': '#9ca3af',
        'on-surface': '#FFFFFF',
        'on-secondary-fixed': '#111111',
        'background': '#080808',
        'tertiary-container': '#202020',
        'surface-bright': '#202020',
        'on-primary': '#ffffff',
        'primary': '#FF6B00',
        'surface-variant': '#111111',
        'on-primary-fixed-variant': '#9a3412',
        'secondary-container': '#181818',
        'primary-container': '#FF6B00',
        'on-secondary-container': '#D1D5DB',
        'on-primary-fixed': '#431407',
        'tertiary': '#9ca3af',
        'secondary': '#D1D5DB',
        'on-error-container': '#fca5a5',
        'surface-container': '#181818',
        'on-tertiary': '#111111',
        'on-surface-variant': '#D1D5DB',
        'on-secondary': '#111111',
        'surface-container-highest': '#202020',
        'surface-dim': '#080808',
        'on-tertiary-container': '#FFFFFF',
        'error-container': '#7f1d1d',
        'on-primary-container': '#ffffff',
        'on-tertiary-fixed-variant': '#9ca3af',
        'outline-variant': '#2A2A2A',
        'on-tertiary-fixed': '#111111',
        'surface-container-low': '#0d0d0d',
        'on-background': '#FFFFFF',
        'industrial-border': '#2A2A2A',
        'in-stock': '#22c55e',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'stack-lg': '24px',
        'stack-md': '12px',
        'gutter': '24px',
        'stack-sm': '4px',
        'base': '8px',
        'margin-mobile': '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { 'lineHeight': '32px', 'fontWeight': '700' }],
        'body-lg': ['16px', { 'lineHeight': '24px', 'fontWeight': '400' }],
        'title-md': ['20px', { 'lineHeight': '28px', 'fontWeight': '600' }],
        'display-lg': ['48px', { 'lineHeight': '56px', 'letterSpacing': '-0.02em', 'fontWeight': '800' }],
        'body-sm': ['14px', { 'lineHeight': '20px', 'fontWeight': '400' }],
        'label-caps': ['12px', { 'lineHeight': '16px', 'letterSpacing': '0.05em', 'fontWeight': '600' }],
        'headline-lg': ['32px', { 'lineHeight': '40px', 'letterSpacing': '-0.01em', 'fontWeight': '700' }],
      },
    },
  },
  plugins: [],
};
