/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error': '#ef4444',
        'primary-fixed-dim': '#EA580C',
        'primary-fixed': '#ffedd5',
        'tertiary-fixed-dim': '#737373',
        'surface-container-high': '#232629',
        'outline': '#737373',
        'tertiary-fixed': '#2D3033',
        'inverse-on-surface': '#F5F5F5',
        'inverse-surface': '#151719',
        'inverse-primary': '#F97316',
        'secondary-fixed-dim': '#737373',
        'surface': '#0D0F10',
        'secondary-fixed': '#2D3033',
        'on-error': '#ffffff',
        'surface-container-lowest': '#08090A',
        'surface-tint': '#F97316',
        'on-secondary-fixed-variant': '#737373',
        'on-surface': '#F5F5F5',
        'on-secondary-fixed': '#151719',
        'background': '#0D0F10',
        'tertiary-container': '#232629',
        'surface-bright': '#232629',
        'on-primary': '#ffffff',
        'primary': '#F97316',
        'surface-variant': '#151719',
        'on-primary-fixed-variant': '#c2410c',
        'secondary-container': '#1C1F21',
        'primary-container': '#F97316',
        'on-secondary-container': '#A3A3A3',
        'on-primary-fixed': '#431407',
        'tertiary': '#737373',
        'secondary': '#A3A3A3',
        'on-error-container': '#fca5a5',
        'surface-container': '#1C1F21',
        'on-tertiary': '#151719',
        'on-surface-variant': '#A3A3A3',
        'on-secondary': '#151719',
        'surface-container-highest': '#232629',
        'surface-dim': '#0D0F10',
        'on-tertiary-container': '#F5F5F5',
        'error-container': '#7f1d1d',
        'on-primary-container': '#ffffff',
        'on-tertiary-fixed-variant': '#737373',
        'outline-variant': '#2D3033',
        'on-tertiary-fixed': '#151719',
        'surface-container-low': '#111314',
        'on-background': '#F5F5F5',
        'industrial-border': '#2D3033',
        'in-stock': '#22c55e',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'stack-lg': '24px',
        'stack-md': '12px',
        'gutter': '24px',
        'stack-sm': '4px',
        'base': '8px',
        'margin-mobile': '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { 'lineHeight': '32px', 'fontWeight': '700' }],
        'body-lg': ['16px', { 'lineHeight': '24px', 'fontWeight': '400' }],
        'title-md': ['20px', { 'lineHeight': '28px', 'fontWeight': '600' }],
        'display-lg': ['48px', { 'lineHeight': '56px', 'letterSpacing': '-0.02em', 'fontWeight': '800' }],
        'body-sm': ['14px', { 'lineHeight': '20px', 'fontWeight': '400' }],
        'label-caps': ['12px', { 'lineHeight': '16px', 'letterSpacing': '0.05em', 'fontWeight': '600' }],
        'headline-lg': ['32px', { 'lineHeight': '40px', 'letterSpacing': '-0.01em', 'fontWeight': '700' }],
      },
    },
  },
  plugins: [],
};
